/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airport;


import static airport.erecord.jTable1e;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CX0140TX
 */
public class emp extends javax.swing.JFrame {

    /**
     * Creates new form emp
     */
    public emp() {
      //this.setUndecorated(true);
      //this.setAlwaysOnTop(true);
      this.setResizable(false);
      this.setVisible(true);
      initComponents();
      Toolkit tk=Toolkit.getDefaultToolkit();
              
              int xsize =(int) tk.getScreenSize().getWidth();
              int ysize =(int) tk.getScreenSize().getWidth();
              
              this.setSize(xsize,ysize);
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField4 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1140, 210, 100, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Contact No");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 340, 140, 35);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Employee Id");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 220, 170, 35);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Post");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(140, 460, 70, 35);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Address");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(1130, 350, 130, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Salary");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(1130, 470, 110, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Nationality");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(120, 600, 160, 35);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Airport Id");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(1120, 600, 130, 40);

        jTextField1.setFont(new java.awt.Font("Yu Gothic", 1, 20)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(420, 210, 290, 40);

        jTextField2.setFont(new java.awt.Font("Yu Gothic", 1, 20)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(420, 340, 290, 40);

        jTextField3.setFont(new java.awt.Font("Yu Gothic", 1, 20)); // NOI18N
        getContentPane().add(jTextField3);
        jTextField3.setBounds(1370, 350, 290, 40);

        jTextField5.setFont(new java.awt.Font("Yu Gothic", 1, 20)); // NOI18N
        getContentPane().add(jTextField5);
        jTextField5.setBounds(1370, 210, 290, 40);

        jTextField6.setFont(new java.awt.Font("Yu Gothic", 1, 20)); // NOI18N
        getContentPane().add(jTextField6);
        jTextField6.setBounds(420, 610, 290, 40);

        jTextField7.setFont(new java.awt.Font("Yu Gothic", 1, 20)); // NOI18N
        getContentPane().add(jTextField7);
        jTextField7.setBounds(1370, 480, 290, 40);

        jComboBox2.setFont(new java.awt.Font("Yu Gothic", 1, 20)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "FlightAttendence", "Technician", "Airhostess", "Pilot", "FlightInstructor", "AirTrafficController", "PassengerServiceagent" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(420, 470, 290, 40);

        jTextField4.setFont(new java.awt.Font("Yu Gothic", 1, 20)); // NOI18N
        getContentPane().add(jTextField4);
        jTextField4.setBounds(1370, 600, 290, 40);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setText("Record Show");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(1380, 840, 250, 50);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton7.setText("Update");
        jButton7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(1070, 840, 130, 50);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(790, 840, 120, 50);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(480, 840, 130, 50);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(190, 840, 130, 50);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel11.setText("Employee Registration");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(800, 80, 360, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\pics\\damian-hutter-61654-unsplash.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-70, -80, 2050, 1270);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new home().setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{

            Class.forName("java.sql.Driver");
            Connection conn;
            conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/airline","root","root");
            String query="insert into employee values(?,?,?,?,?,?,?,?)";
            PreparedStatement pst=conn.prepareStatement(query);
            pst.setInt(1,Integer.parseInt(jTextField1.getText()));
            pst.setString(2,jTextField3.getText());
            pst.setInt(3,Integer.parseInt(jTextField2.getText()));
            pst.setString(4,jTextField5.getText());
            pst.setString(5,jComboBox2.getSelectedItem().toString());
            pst.setInt(6,Integer.parseInt(jTextField7.getText()));
            pst.setString(7,jTextField6.getText());
            pst.setInt(8,Integer.parseInt(jTextField4.getText()));
          
           
            pst.execute();
            JOptionPane.showMessageDialog(null,"saved succesfully");

        }  catch (SQLException ex) {
            Logger.getLogger(flight.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(flight.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try{
            Class.forName("java.sql.Driver");
            Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/airline","root","root");

            String sql="update employee set  ename = ?,contactno = ?, address= ?, post= ?,  salary= ?, nationality= ?, airpotid = ? where  eid= ?";

            PreparedStatement pstmt=conn.prepareStatement(sql);
             pstmt.setString(1,jTextField3.getText());
              pstmt.setString(2,jTextField2.getText());
               pstmt.setString(3,jTextField5.getText());
               pstmt.setString(4,jComboBox2.getSelectedItem().toString());
           
            pstmt.setString(5,jTextField7.getText());
            pstmt.setString(6,jTextField6.getText());
             pstmt.setString(7,jTextField4.getText());
            pstmt.setString(8,jTextField1.getText());

            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null,"Record updated successfully");
            conn.close();

        }  catch (ClassNotFoundException ex) {
            Logger.getLogger(flight.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(flight.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        erecord s=new erecord();
         DefaultTableModel model=(DefaultTableModel)jTable1e.getModel();
        try{
            Class.forName("java.sql.Driver");
            Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/airline","root","root");
            Statement st=conn.createStatement();
            String query="Select * from employee";
            ResultSet rs=st.executeQuery(query);
            while(rs.next()) {
                String d1=rs.getString("eid");
                String d2=rs.getString("ename");
                String d3=rs.getString("contactno");
                String d4=rs.getString("address");
                String d5=rs.getString("post");
                String d6=rs.getString("salary");
                String d7=rs.getString("nationality");
                String d8=rs.getString("airpotid");
                
                model.addRow(new Object[] {d1,d2,d3,d4,d5,d6,d7,d8});

            }
            rs.close();
            st.close();
            conn.close();

        } catch (Exception ex) {
        }
        s.setVisible(true);
        dispose();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
             String sql=" delete from employee where eid=?;";
      try{
          Class.forName("java.sql.Driver");
            Connection conn;
             conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/airline","root","root");
              PreparedStatement pst=null;
           pst=conn.prepareStatement(sql);
           pst.setString(1, jTextField1.getText());
           
           pst.execute();
           JOptionPane.showMessageDialog(null,"Deleted");
           
           
      } catch (SQLException ex) {
            Logger.getLogger(flight.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(flight.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new emp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    public static javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
