/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airport;
import javax.swing.JOptionPane;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/**
 *
 * @author CX0140TX
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
     public home() {
      //this.setUndecorated(true);
      //this.setAlwaysOnTop(true);
      this.setResizable(false);
      this.setVisible(true);
      initComponents();
      Toolkit tk=Toolkit.getDefaultToolkit();
              
              int xsize =(int) tk.getScreenSize().getWidth();
              int ysize =(int) tk.getScreenSize().getWidth();
              
              this.setSize(xsize,ysize);
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        f1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        p1 = new javax.swing.JButton();
        t1 = new javax.swing.JButton();
        e1 = new javax.swing.JButton();
        es1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Sitka Subheading", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AIRLINE FLIGHT MANAGEMENT SYSTEM");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(520, 40, 937, 53);

        f1.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        f1.setText("Flight");
        f1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f1ActionPerformed(evt);
            }
        });
        getContentPane().add(f1);
        f1.setBounds(150, 260, 333, 50);

        jButton3.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        jButton3.setText("Logout");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(150, 804, 333, 50);

        p1.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        p1.setText("Passenger");
        p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1ActionPerformed(evt);
            }
        });
        getContentPane().add(p1);
        p1.setBounds(150, 370, 333, 50);

        t1.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        t1.setText("Ticket");
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(153, 590, 330, 50);

        e1.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        e1.setText("Employee");
        e1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e1ActionPerformed(evt);
            }
        });
        getContentPane().add(e1);
        e1.setBounds(150, 480, 333, 50);

        es1.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        es1.setText("Airport");
        es1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        es1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        es1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                es1ActionPerformed(evt);
            }
        });
        getContentPane().add(es1);
        es1.setBounds(150, 145, 333, 50);

        jButton1.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        jButton1.setText("About");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(150, 695, 330, 55);

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\pics\\airplane-wallpaper-11.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1920, 1070);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         login l=new login();
         l.setVisible(true);    
          dispose();
        //System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void f1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f1ActionPerformed
      new flight().setVisible(true);
       dispose();
    }//GEN-LAST:event_f1ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
       new Ticket().setVisible(true);
        dispose();
    }//GEN-LAST:event_t1ActionPerformed

    private void p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1ActionPerformed
      new pasger ().setVisible(true);
       dispose();
    }//GEN-LAST:event_p1ActionPerformed

    private void e1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e1ActionPerformed
      new emp().setVisible(true);
       dispose();
    }//GEN-LAST:event_e1ActionPerformed

    private void es1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_es1ActionPerformed
        new app().setVisible(true);
         dispose();
    }//GEN-LAST:event_es1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         new qur().setVisible(true);
                   dispose();          
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton e1;
    private javax.swing.JButton es1;
    private javax.swing.JButton f1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton p1;
    private javax.swing.JButton t1;
    // End of variables declaration//GEN-END:variables

private void systemExit()
{
    WindowEvent winCloseing=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
}

    


}
