/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airport;


import static airport.ap.jTable1ap;
import static airport.flight1.dh1;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author CX0140TX
 */
public class pasgerqu extends javax.swing.JFrame {

     ResultSet rs=null;
    prepareStatement pst=null;
    
    public pasgerqu() {
      //this.setUndecorated(true);
     // this.setAlwaysOnTop(true);
      this.setResizable(false);
      this.setVisible(true);
      initComponents();
      Toolkit tk=Toolkit.getDefaultToolkit();
              
              int xsize =(int) tk.getScreenSize().getWidth();
              int ysize =(int) tk.getScreenSize().getWidth();
              
              this.setSize(xsize,ysize);
              
              
             
            // making transperent
            
             jTable1.setBackground(new Color(0,0,0,0));
              ((DefaultTableCellRenderer) jTable1.getDefaultRenderer(Object.class)).setBackground(new Color(0,0,0,0));
             // jTable1ap.setGridColor(Color.white);
              jTable1.setForeground(Color.black);
             //jScrollPane1 scrollPane =new jScrollPanel(jTable1ap);
              jScrollPane1.setBackground(new Color(0,0,0,0));
              jScrollPane1.setOpaque(false);
              jTable1.setOpaque(false);
              ((DefaultTableCellRenderer) jTable1.getDefaultRenderer(Object.class)).setOpaque(false);
              jScrollPane1.getViewport().setOpaque(false);
              
              
              
             //making transprent
             
              jTable2.setBackground(new Color(0,0,0,0));
              ((DefaultTableCellRenderer) jTable2.getDefaultRenderer(Object.class)).setBackground(new Color(0,0,0,0));
             // jTable1ap.setGridColor(Color.white);
              jTable2.setForeground(Color.black);
             //jScrollPane1 scrollPane =new jScrollPanel(jTable1ap);
              jScrollPane2.setBackground(new Color(0,0,0,0));
              jScrollPane2.setOpaque(false);
              jTable2.setOpaque(false);
              ((DefaultTableCellRenderer) jTable2.getDefaultRenderer(Object.class)).setOpaque(false);
              jScrollPane2.getViewport().setOpaque(false);
              
              
            
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(330, 140, 154, 29);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PassengerName", "FlightNo", "FlightName", "AirpotId", "AirpotName", "From", "To", "Departuredate", "AirvalDate"
            }
        ));
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(110, 230, 950, 420);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Passenger Gender ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1310, 150, 230, 40);

        jTable2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Gender", "Count"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(1310, 230, 490, 160);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Go");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1710, 430, 80, 50);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(990, 820, 90, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Passenger Id");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 140, 172, 29);

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\pics\\pexels-photo-1110670.jpeg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1920, 1280);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
   DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        try{
           
             Class.forName("com.mysql.jdbc.Driver");
            Connection conn;
             conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/airline","root","root");
          String sql="select p.p_name, f.FlightNo,f.FlightName,a.airpotid,a.airpotname,f.AFrom,f.ATo,f.Departuredate,f.AirvalDate from passenger p,flight f,airpot a where p.p_id=? and p.FlightNo=f.FlightNo and a.airpotid=f.airpotid";
          PreparedStatement pst=conn.prepareStatement(sql);
          pst.setString(1,jTextField1.getText());
          rs=pst.executeQuery();
          if(rs.next()){
              String add1=rs.getString("p_name");
              
               String add2=rs.getString("FlightNo");
             
               String add3=rs.getString("FlightName");
              
               String add4=rs.getString("airpotid");
              
               String add5=rs.getString("airpotname");
             
               String add6=rs.getString("AFrom");
              
               String add7=rs.getString("ATo");
              
               String add8=rs.getString("Departuredate");
             
               String add9=rs.getString("AirvalDate");
               model.addRow(new Object[] {add1,add2,add3,add4,add5,add6,add7,add8,add9});
               jTextField1.setText(null);  
          }
          
      }
      catch(Exception e)
      {
          JOptionPane.showMessageDialog(null,e);
      
    }//GEN-LAST:event_jTextField1KeyReleased
    
    }
    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased

    }//GEN-LAST:event_jTable1KeyReleased

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      DefaultTableModel model=(DefaultTableModel)jTable2.getModel();
        try{
           
            Class.forName("java.sql.Driver");
            Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/airline","root","root");
            Statement st=conn.createStatement();
            String query="select gender,count(gender)from passenger group by gender";

            ResultSet rs=st.executeQuery(query);
            while(rs.next()) {
                String d1=rs.getString("gender");
                String d2=rs.getString("count(gender)");
                 model.addRow(new Object[] {d1,d2});

            }
            rs.close();
            st.close();
            conn.close();

        } catch (Exception ex) {
           
        }        // TODO add your handling code // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          new qur().setVisible(true);
          dispose();            
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
 
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        try{
           
             Class.forName("com.mysql.jdbc.Driver");
            Connection conn;
             conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/airline","root","root");
          String sql="select p.p_name, f.FlightNo,f.FlightName,a.airpotid,a.airpotname,f.AFrom,f.ATo,f.Departuredate,f.AirvalDate from passenger p,flight f,airpot a where p.p_id=? and p.FlightNo=f.FlightNo and a.airpotid=f.airpotid";
          PreparedStatement pst=conn.prepareStatement(sql);
          pst.setString(1,jTextField1.getText());
          rs=pst.executeQuery();
          if(rs.next()){
              String add1=rs.getString("p_name");
              
               String add2=rs.getString("FlightNo");
             
               String add3=rs.getString("FlightName");
              
               String add4=rs.getString("airpotid");
              
               String add5=rs.getString("airpotname");
             
               String add6=rs.getString("AFrom");
              
               String add7=rs.getString("ATo");
              
               String add8=rs.getString("Departuredate");
             
               String add9=rs.getString("AirvalDate");
               model.addRow(new Object[] {add1,add2,add3,add4,add5,add6,add7,add8,add9});
               jTextField1.setText(null);  
          }
          
      }
      catch(Exception e)
      {
          JOptionPane.showMessageDialog(null,e);
      
    }                                       
    
    }//GEN-LAST:event_jTextField1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pasgerqu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pasgerqu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pasgerqu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pasgerqu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pasgerqu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void jTable(String add1) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void jTable1(String add1) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
